env:
  es6: true
  node: true
  browser: true
  commonjs: true
  jest: true

extends: ['airbnb-base', 'eslint:recommended', 'plugin:react/recommended']

parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins: ['react']

settings:
  react:
    version: '17'

rules:
  no-alert: 0
  no-console: 0
  import/extensions: 0
  import/no-named-as-default: 0
  import/prefer-default-export: 0
  default-param-last: 0
  no-unused-expressions: 0
  object-curly-newline: 0
  no-use-before-define: 0
  linebreak-style: 0
